FROM almalinux/8-minimal

LABEL fr.erz.author="Lucian BLETAN" \
      description="DinD AlmaLinux 8 minimal"

RUN curl -L "https://download.docker.com/linux/centos/docker-ce.repo" -o /etc/yum.repos.d/docker-ce.repo

RUN microdnf -y update && \
    microdnf -y install docker-ce docker-ce-cli containerd.io && \
    microdnf clean all

RUN curl -L "https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

ENTRYPOINT ["dockerd"]
